import { useState } from 'react'
import { ArrowRight, ArrowUpRight, CircleGauge, Plus, Wallet } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useAuth } from '../auth-context'
import { Empty, ErrorNotice, Loading, PageTitle, PredictionList, VehicleIcon } from '../components'
import { useRemote } from '../hooks'
import type { Dashboard as DashboardData } from '../types'
import { money, vehicleTypes } from '../types'
export default function Dashboard() {
  const { user } = useAuth(), [retry, setRetry] = useState(0)
  const { data, error, loading } = useRemote<DashboardData>('/dashboard', retry)
  return <div className="page-wrap"><PageTitle eyebrow={`WELCOME BACK, ${user?.display_name.split(' ')[0].toUpperCase()}`} title="YOUR GARAGE. YOUR PERSPECTIVE." description="All your rides and estimates, in one place." action={<Link className="button primary" to="/predict"><Plus size={18} aria-hidden="true" />New estimate</Link>} />{loading ? <Loading /> : error ? <><ErrorNotice>{error}</ErrorNotice><button className="button secondary" onClick={() => setRetry(value => value + 1)}>Try again</button></> : data && <><div className="stats-grid"><section className="stat-card"><div><span>Total estimates</span><CircleGauge size={18} aria-hidden="true" /></div><strong>{data.total_predictions.toString().padStart(2, '0')}</strong><p>Every vehicle you’ve valued</p></section><section className="stat-card"><div><span>Average estimated value</span><Wallet size={18} aria-hidden="true" /></div><strong className="stat-price">{data.average_price === null ? '—' : <><small>NPR</small> {money(data.average_price)}</>}</strong><p>Across your saved predictions</p></section><section className="stat-card garage-mix"><div><span>Your garage at a glance</span><ArrowUpRight size={18} aria-hidden="true" /></div><div className="type-counts">{vehicleTypes.map(type => <Link to={`/history?type=${type}`} key={type}><VehicleIcon type={type} size={24} /><strong>{data.by_type[type]}</strong><span>{type === 'Car' ? 'Cars' : type === 'Bike' ? 'Bikes' : 'Scooters'}</span></Link>)}</div></section></div><section className="panel recent-panel"><div className="panel-heading"><div><p className="eyebrow">YOUR LATEST MILES</p><h2>Recent estimates</h2></div><Link to="/history" className="text-link">View all <ArrowRight size={16} aria-hidden="true" /></Link></div>{data.recent.length ? <PredictionList predictions={data.recent} /> : <Empty />}</section><section className="garage-banner"><div><p className="eyebrow">THE NEXT CHAPTER IS YOURS</p><h2>Got another ride in mind?</h2><p>Bring a little more perspective to the decision.</p></div><Link to="/predict" className="button secondary">Create an estimate <ArrowUpRight size={18} aria-hidden="true" /></Link></section></>}</div>
}
