import { useState } from 'react'
import type { FormEvent } from 'react'
import { ArrowRight, ArrowUpRight, FileText, MapPin, ShieldCheck } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { VehicleIcon } from '../components'
import { useRemote } from '../hooks'
import { vehicleTypes } from '../types'
import type { VehicleType } from '../types'
export default function Home() {
  const [type, setType] = useState<VehicleType>('Car'), [brand, setBrand] = useState('')
  const { data: brands, loading, error } = useRemote<string[]>(`/catalog/brands?vehicle_type=${type}`)
  const navigate = useNavigate()
  function start(event: FormEvent<HTMLFormElement>) { event.preventDefault(); navigate(`/predict?type=${type}${brand ? `&brand=${encodeURIComponent(brand)}` : ''}`) }
  return <div className="home-page"><section className="hero" aria-labelledby="hero-title"><img className="hero-image" src="/images/nepal-rides-hero.webp" alt="" fetchPriority="high" width="1672" height="941" /><div className="hero-shade" /><div className="hero-content"><span className="hero-kicker"><span className="tiny-dot" /> A NEW PERSPECTIVE ON PRE-OWNED.</span><h1 id="hero-title">KNOW YOUR RIDE.<br /><span>KNOW ITS VALUE.</span></h1><p>Every kilometre tells a story.<br />Find a starting price for the next chapter.</p><Link to="/predict" className="button primary">Value your vehicle <ArrowUpRight size={19} aria-hidden="true" /></Link><Link to="/about" className="hero-secondary">Meet SmartSauda <ArrowRight size={16} aria-hidden="true" /></Link></div><span className="hero-location"><MapPin size={13} aria-hidden="true" /> INSPIRED BY THE ROADS OF NEPAL</span></section>
    <section className="quick-start panel" aria-labelledby="quick-title"><div className="quick-heading"><div><p className="eyebrow">YOUR NEXT MOVE</p><h2 id="quick-title">What are you riding?</h2></div><span className="muted small">A few details. A clearer starting point.</span></div><form onSubmit={start}><fieldset className="type-tabs"><legend className="sr-only">Vehicle type</legend>{vehicleTypes.map(kind => <label key={kind} className={kind === type ? 'selected' : ''}><input type="radio" name="quick-type" value={kind} checked={kind === type} onChange={() => { setType(kind); setBrand('') }} /><VehicleIcon type={kind} size={20} />{kind === 'Car' ? 'Cars' : kind === 'Bike' ? 'Bikes' : 'Scooters'}</label>)}</fieldset><div className="quick-controls"><label className="field"><span>Vehicle brand</span><select value={brand} onChange={event => setBrand(event.target.value)} disabled={loading}><option value="">{loading ? 'Loading brands…' : 'Choose a brand'}</option>{brands?.map(item => <option key={item}>{item}</option>)}</select></label><div className="quick-market"><MapPin size={18} aria-hidden="true" /><div><span>Your market</span><strong>Nepal <small>· NPR</small></strong></div></div><button className="button primary" type="submit">Let’s find its value <ArrowRight size={18} aria-hidden="true" /></button></div>{error && <p className="error-text" role="alert">Brands are unavailable. You can still enter your vehicle on the next page.</p>}</form></section>
    <div className="trust-strip"><span><ShieldCheck size={17} aria-hidden="true" /> Your estimates, saved privately</span><span><FileText size={17} aria-hidden="true" /> A report you can take with you</span><span><MapPin size={17} aria-hidden="true" /> Built around Nepal’s vehicles</span></div>
    <section className="home-section"><div className="section-heading"><div><p className="eyebrow">DIFFERENT RIDES. DIFFERENT STORIES.</p><h2>One destination. Your next good deal.</h2></div><Link to="/about" className="text-link">How it works <ArrowUpRight size={16} aria-hidden="true" /></Link></div><div className="category-grid">{vehicleTypes.map((kind, index) => <Link key={kind} to={`/predict?type=${kind}`} className={`category-card category-${kind.toLowerCase()}`}><img className="category-photo" src={`/api/v1/assets/vehicles/${kind.toLowerCase()}.jpg`} alt={`Real ${kind.toLowerCase()} photo`} loading="lazy" /><span className="category-number">0{index + 1} /</span><div><h3>{kind === 'Car' ? 'FOUR WHEELS. ENDLESS POSSIBILITIES.' : kind === 'Bike' ? 'TWO WHEELS. YOUR OWN WAY.' : 'CITY STREETS. EVERYDAY FREEDOM.'}</h3><span>Value your {kind.toLowerCase()} <ArrowUpRight size={18} aria-hidden="true" /></span></div></Link>)}</div></section>
    <section className="approach-band"><div><p className="eyebrow">A PRICE WITH PERSPECTIVE</p><h2>MORE CLARITY.<br />LESS GUESSWORK.</h2></div><div><p>Start with an estimate informed by vehicle age, kilometres and available specifications. Keep your history together and download a report for the conversation ahead.</p><p className="muted small">Our models learn from historical Nepal datasets. Every result includes its limitations; an estimate is a starting point, not a guaranteed sale price.</p><Link className="text-link" to="/about#data">Look under the bonnet <ArrowUpRight size={16} aria-hidden="true" /></Link></div></section>
  </div>
}
