import { useState } from 'react'
import type { FormEvent } from 'react'
import { Check, LockKeyhole, ShieldCheck } from 'lucide-react'
import { useAuth } from '../auth-context'
import { api, errorMessage } from '../api'
import { ErrorNotice, Loading, PageTitle } from '../components'
import { useRemote } from '../hooks'
import type { User } from '../types'
import { date } from '../types'
function AdminPanel() {
  const { user } = useAuth(), [offset, setOffset] = useState(0), [refresh, setRefresh] = useState(0), [error, setError] = useState(''), [busy, setBusy] = useState('')
  const accounts = useRemote<{ items: User[]; total: number }>(`/admin/users?limit=10&offset=${offset}`, refresh)
  const stats = useRemote<{ users: number; active_users: number; predictions: number }>('/admin/stats', refresh)
  async function change(account: User) { setBusy(account.id); setError(''); try { await api(`/admin/users/${account.id}/status`, { method: 'PATCH', body: JSON.stringify({ active: !account.active }) }); setRefresh(value => value + 1) } catch (error) { setError(errorMessage(error)) } finally { setBusy('') } }
  return <section className="panel admin-panel"><div className="panel-heading"><div><p className="eyebrow">ADMINISTRATOR</p><h2>Account management</h2></div><ShieldCheck size={22} aria-hidden="true" /></div><p className="muted">Manage account access. Other users’ individual predictions and reports remain private.</p>{stats.data && <div className="admin-stats"><span><strong>{stats.data.users}</strong> accounts</span><span><strong>{stats.data.active_users}</strong> active</span><span><strong>{stats.data.predictions}</strong> predictions</span></div>}{(error || accounts.error || stats.error) && <ErrorNotice>{error || accounts.error || stats.error}</ErrorNotice>}{accounts.loading ? <Loading /> : accounts.data && <><div className="table-scroll"><table><caption className="sr-only">Registered accounts</caption><thead><tr><th>Name / email</th><th>Role</th><th>Status</th><th>Account access</th></tr></thead><tbody>{accounts.data.items.map(account => <tr key={account.id}><td><strong>{account.display_name}</strong><small className="table-email">{account.email}</small></td><td>{account.role}</td><td>{account.active ? 'Active' : 'Disabled'}</td><td><button className="button subtle compact" disabled={account.id === user?.id || Boolean(busy)} onClick={() => void change(account)}>{busy === account.id ? 'Updating…' : account.active ? 'Disable account' : 'Enable account'}</button></td></tr>)}</tbody></table></div><div className="pagination"><span>{accounts.data.total} accounts</span><div><button className="button subtle compact" disabled={offset === 0} onClick={() => setOffset(value => value - 10)}>Previous</button><button className="button subtle compact" disabled={offset + 10 >= accounts.data.total} onClick={() => setOffset(value => value + 10)}>Next</button></div></div></>}</section>
}
export default function Profile() {
  const { user, updateUser } = useAuth()
  const [name, setName] = useState(user?.display_name || ''), [busy, setBusy] = useState(''), [error, setError] = useState(''), [success, setSuccess] = useState('')
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy('profile'); setError(''); setSuccess(''); try { const updated = await api<User>('/profile', { method: 'PATCH', body: JSON.stringify({ display_name: name }) }); updateUser(updated); setSuccess('Your profile has been updated.') } catch (error) { setError(errorMessage(error)) } finally { setBusy('') } }
  async function password(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); if (form.get('new_password') !== form.get('confirm_password')) { setError('Your new passwords don’t match.'); return } setBusy('password'); setError(''); setSuccess(''); try { await api('/profile/password', { method: 'POST', body: JSON.stringify({ current_password: form.get('current_password'), new_password: form.get('new_password') }) }); window.location.replace('/signin?password=changed') } catch (error) { setError(errorMessage(error)) } finally { setBusy('') } }
  return <div className="page-wrap"><PageTitle eyebrow="A SPACE THAT’S YOURS" title="YOUR PROFILE." description="The details behind your garage." />{error && <ErrorNotice>{error}</ErrorNotice>}{success && <div className="notice success" role="status"><Check size={18} aria-hidden="true" />{success}</div>}<div className="profile-grid"><section className="panel profile-details"><div className="profile-summary"><span className="avatar large">{user?.display_name.charAt(0).toUpperCase()}</span><div><h2>{user?.display_name}</h2><span className="tag">{user?.role} account</span></div></div><form onSubmit={save}><label className="field"><span>Display name</span><input required maxLength={80} value={name} onChange={event => setName(event.target.value)} autoComplete="name" /></label><label className="field"><span>Email address</span><input value={user?.email || ''} readOnly type="email" /><small className="field-hint">Your account email cannot be changed here.</small></label><p className="small muted">Member since {user && date(user.created_at)}</p><button className="button primary" disabled={Boolean(busy)}>{busy === 'profile' ? 'Saving…' : 'Save profile'}</button></form></section><section className="panel password-panel"><div className="panel-heading"><h2>Keep your garage secure</h2><LockKeyhole size={21} aria-hidden="true" /></div><p className="muted small">Changing your password signs you out on every device.</p><form onSubmit={password}><label className="field"><span>Current password</span><input required type="password" name="current_password" autoComplete="current-password" maxLength={128} /></label><label className="field"><span>New password</span><input required type="password" name="new_password" autoComplete="new-password" minLength={12} maxLength={128} /><small className="field-hint">At least 12 characters.</small></label><label className="field"><span>Confirm new password</span><input required type="password" name="confirm_password" autoComplete="new-password" minLength={12} maxLength={128} /></label><button className="button secondary" disabled={Boolean(busy)}>{busy === 'password' ? 'Updating…' : 'Update password'}</button></form></section></div>{user?.role === 'Admin' && <AdminPanel />}</div>
}
