import { useEffect, useState } from 'react'
import { ArrowUpRight, ChevronRight, CircleHelp, Gauge, History, Home, LogOut, Menu, ShieldCheck, UserRound, X } from 'lucide-react'
import { Link, NavLink, Outlet, useLocation } from 'react-router-dom'
import { useAuth } from './auth-context'
import { errorMessage } from './api'
export function Logo() { return <Link to="/" className="logo" aria-label="SmartSauda home"><span className="logo-mark" aria-hidden="true">S<span /></span><span>smart<span className="logo-light">sauda</span><small>KNOW YOUR NEXT MOVE.</small></span></Link> }
export default function Layout() {
  const { user, signOut } = useAuth(); const location = useLocation()
  const [openPath, setOpenPath] = useState<string | null>(null), [error, setError] = useState('')
  const open = openPath === location.pathname
  useEffect(() => {
    window.scrollTo(0, 0)
    const names: Record<string, string> = { '/': 'Explore', '/predict': 'Value your vehicle', '/dashboard': 'Your garage', '/history': 'Prediction history', '/about': 'Our approach', '/signin': 'Sign in', '/signup': 'Create account', '/profile': 'Your profile' }
    document.title = `${names[location.pathname] || 'Your estimate'} — SmartSauda`
    document.getElementById('main-content')?.focus({ preventScroll: true })
  }, [location.pathname])
  useEffect(() => { if (!open) return; const close = (event: KeyboardEvent) => { if (event.key === 'Escape') setOpenPath(null) }; window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close) }, [open])
  const navigation = [{ path: '/', label: 'Explore', icon: Home }, { path: '/predict', label: 'Value your vehicle', icon: Gauge }, { path: '/dashboard', label: 'Your garage', icon: ShieldCheck }, { path: '/history', label: 'Prediction history', icon: History }]
  async function logout() { try { await signOut() } catch (error) { setError(errorMessage(error)) } }
  return <div className="app-shell"><a className="skip-link" href="#main-content">Skip to content</a><header className="mobile-header"><Logo /><button aria-label={open ? 'Close navigation' : 'Open navigation'} aria-expanded={open} aria-controls="sidebar" className="icon-button" onClick={() => setOpenPath(open ? null : location.pathname)}>{open ? <X /> : <Menu />}</button></header>{open && <button className="nav-scrim" aria-label="Close navigation" onClick={() => setOpenPath(null)} />}
    <aside id="sidebar" className={`sidebar ${open ? 'is-open' : ''}`}><div className="desktop-logo"><Logo /></div><p className="nav-label">THE ROAD AHEAD</p><nav aria-label="Main navigation">{navigation.map(({ path, label, icon: Icon }) => <NavLink key={path} to={path} end={path === '/'}><Icon size={19} aria-hidden="true" /><span>{label}</span><ChevronRight className="nav-chevron" size={15} aria-hidden="true" /></NavLink>)}</nav><div className="sidebar-note"><span className="tiny-dot" />MADE FOR NEPAL<p>A little more clarity.<br />Before your next move.</p><span className="coordinate">27.7172° N &nbsp; 85.3240° E</span></div><nav className="secondary-nav" aria-label="Account and information"><NavLink to="/about"><CircleHelp size={18} aria-hidden="true" />Our approach</NavLink>{user && <NavLink to="/profile"><UserRound size={18} aria-hidden="true" />Your profile</NavLink>}</nav><div className="sidebar-account">{user ? <><Link to="/profile" className="account-link"><span className="avatar">{user.display_name.charAt(0).toUpperCase()}</span><span><strong>{user.display_name}</strong><small>{user.role} account</small></span></Link><button className="icon-button" aria-label="Sign out" onClick={() => void logout()}><LogOut size={17} /></button></> : <Link to="/signin" className="account-link"><span className="avatar"><UserRound size={19} aria-hidden="true" /></span><span><strong>Your own garage</strong><small>Sign in to get started</small></span><ArrowUpRight size={16} aria-hidden="true" /></Link>}</div>{error && <p className="error-text" role="alert">{error}</p>}</aside>
    <div className="main-shell"><header className="topbar"><div><span className="tiny-dot" /><span>Nepal’s next chapter starts with a smarter deal.</span></div><div className="topbar-actions"><span className="market-label">NEPAL <span>/</span> NPR</span>{user ? <Link to="/profile" className="top-account">{user.display_name.split(' ')[0]} <UserRound size={16} aria-hidden="true" /></Link> : <Link to="/signin" className="text-link">Sign in <ArrowUpRight size={15} aria-hidden="true" /></Link>}</div></header><main id="main-content" tabIndex={-1}><Outlet /></main><footer className="footer"><span>© {new Date().getFullYear()} SmartSauda</span><span>For the journey. And the deal.</span><Link to="/about#data">Our data & limitations <ArrowUpRight size={13} aria-hidden="true" /></Link></footer></div></div>
}
